version: '3'

services:
  ft:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
    environment:
      - BUILD_TAG=1.0.${BUILD_NUMBER}
      - APP_HOSTNAME=app
      - APP_PORT=1080
      - SERVICE_CHECK_URL_PATH=app/version  
    volumes:
      - ./settings/ft-appsettings.json/:/workdir/settings/appsettings.json
      - ./secrets/ft-secrets.json/:/workdir/secrets/secrets.json
    links:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/localdev/Dockerfile
    volumes:
      - ./settings/ft-appsettings.json/:/workdir/settings/appsettings.json
      - ./secrets/ft-secrets.json/:/workdir/secrets/secrets.json
    links:
      - redis

  redis:
    image: redis:4.0.10-alpine
